### ISSUE TITLE
lava texture too large for load my resources mod for 1.20.1 forge

### ISSUE THREAD

**Issue by nekohacker591** [PoeticRainbow/golden-days#56]
[19:20:32] [Render thread/ERROR]:Failed to get filter section from pack loadmyresources.hiddenpack[19:20:32] [Worker-ResourceReload-4/ERROR]:Requested atlas size 256x65536 exceeds maximum of 32768x32768[19:20:33] [Render thread/ERROR]:Reported exception thrown!
net.minecraft.ReportedException: Stitching
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:961) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.5.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.5.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: net.minecraft.client.renderer.texture.StitcherException: Unable to fit: minecraft:block/lava_flow - size: 32x51168 - Maybe try a lower resolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.handler$zgb000$modernfix$stitchFast(Stitcher.java:566) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.texture.Stitcher.m_118193_(Stitcher.java) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.texture.SpriteLoader.m_261295_(SpriteLoader.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.renderer.texture.SpriteLoader.m_260767_(SpriteLoader.java:123) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[19:20:33] [Render thread/FATAL]: Preparing crash report with UUID 866c71a5-be67-4b9f-b2de-7b3b2579adb4
[19:20:33] [Render thread/FATAL]: Preparing crash report with UUID a5826677-d110-483e-ac33-ce12bd642b68

Do not forget to change the title, add labels, and remove this text

**Comment by PoeticRainbow** [comment]
The lava texture shouldn't cause the atlas to be bigger. Did you copy it over and forget the mcmeta file?
